### ISSUE TITLE
QUESTION: How do you use the original filename?

### ISSUE THREAD

**Issue by shaunflagg** [jbesw/askjames-s3uploader#14]
How do you pass the original filename to the upload function so that the original filename is used instead of the random ID?

**Comment by shaunflagg** [comment]
I added filename to the frontend code. I can see the filename in the developer console. How do I pass it to the API and use it in the Lambda?

```
...
data: {
          image: '',
          uploadURL: '',
          fileName: ''
        },
        methods: {
          onFileChange (e) {
            let files = e.target.files || e.dataTransfer.files
            let filename = files[0].name
            console.log(filename);
            if (!files.length) return
            this.createImage(files[0])
          },
     ...
```

**Comment by jbesw** [comment]
Hello! You can pass the name either as a query parameter or part of a JSON body to the API. As a query parameter, it looks like this:

https://abc1234abc.execute-api.us-west-2.amazonaws.com/dev/myApp?filename=myFilename.txt

The query parameter is passed to the Lambda function as part of the event payload. You can access it at event.queryStringParameters. You can deploy an example of this using this pattern from Serverless Land: https://serverlessland.com/patterns/apigw-lambda.

Ensure that you sanitize any filename passed this way, as with any other user input. Also be careful to ensure that in a application with many users, you handle conflicting object keys.

HTH!

**Comment by shaunflagg** [comment]
Thanks @jbesw I will give it a shot. Cheers

**Comment by shaunflagg** [comment]
I was able to get this working with a few minor modifications per https://stackoverflow.com/a/70839866/11341426

**Comment by jbesw** [comment]
Great! Let me know if you have any other questions.
